### ISSUE TITLE
進階搜尋沒勾選還是會用先前勾的選項篩選

### ISSUE THREAD

**Issue by maxam2017** [nctuplus/nctuplus#78]
進階搜尋沒勾選還是會用先前勾的選項篩選

**Comment by ianre657** [comment]
近一步說明:
1. 勾選進階搜尋之後按下搜尋按鈕
![screen shot 2018-03-01 at 11 47 09 pm](https://user-images.githubusercontent.com/13212935/36853999-e3046146-1daa-11e8-8f78-b19a92e61bd4.png)
2. 搜尋完之後->取消勾選進階搜尋按鈕 -> 再按一次搜尋參數仍然會被傳出
![screen shot 2018-03-01 at 11 45 18 pm](https://user-images.githubusercontent.com/13212935/36853933-b48d3964-1daa-11e8-8c8e-a8bbfd93b594.png)

**Comment by ianre657** [comment]
沒有辦法消除的原因是因為取消勾選時觸動的指令預設會將進階搜尋中的第三欄清除掉。但這個動作是直接寫死在html檔案中。後續程式碼的更動卻沒有將原先寫死的程式碼也做修改，才會造成這個問題。
已經暫時把變數名稱改好，問題應該暫時解決了。

**Comment by ianre657** [comment]
在追蹤原始碼的時候發現了幾個問題，可能需要討論討論。
首先是取消進階搜尋按鈕時的行為，究竟是要照著兩年前的行為只消除掉特定開課單位，還是將所有的選項都清空。 @osinoyan 可以在下次聚會時討論討論。

再者，引用一下更改前進階搜尋按鈕所使用到的程式碼
[進階搜尋按鈕的檔案位置](https://github.com/nctuplus/nctuplus/blob/master/app/views/courses/index.html.erb)
`<%=check_box_tag "adv_toggle",params[:adv_toggle],params[:adv_toggle],onchange: "$('#adv-search').toggleClass('hidden');$('#q_department_id_eq').val('');" %>
`
欄位的清空是直接透過jQuery的函式對特定id物件做寫入，但要特別注意，在欄位`分類`中，他的更改方法預設會呼叫其他函式在進行更動。
`<%= select_tag "degree" ,options_for_select(Department.degreeSel,params[:degree]), class: "form-control",:onchange=>"change_degree($(this))" %>`

**Comment by ianre657** [comment]
此外，在進階搜尋的第三欄之中，可以看到預設欄位的值非常兇狠。

以`所有研究所課程為例`，對應到的選項值是`"73 74 75 76 77 78 79 80 81 82 83 84 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 146 152 153 157 158 160 161 162 165"`這個超長字串。

![screen shot 2018-03-22 at 1 47 59 am](https://user-images.githubusercontent.com/13212935/37727608-3fc913b8-2d73-11e8-9bd5-e7b841daf121.png)

這種選項值會讓取消選取時很難回復成預設值。

@deror1869107 不知道後端能不能直接將這些預設欄位的key值直接設為空字串，這樣會比較好寫
