### ISSUE TITLE
同一門課評分沒有合併

### ISSUE THREAD

**Issue by lcd78706** [nctuplus/nctuplus#85]
同一門機器學習概論有各自的評分，應該要合併
在寫心得搜尋課程時，也出現兩筆同樣的課程

![2](https://user-images.githubusercontent.com/23053428/35469900-347ce76e-037a-11e8-9ac0-2634b1e61da3.png)
![3](https://user-images.githubusercontent.com/23053428/35469901-34a2a83c-037a-11e8-8e80-6987838582f6.png)
![1](https://user-images.githubusercontent.com/23053428/35469924-82b1a7b2-037a-11e8-9ab0-3a0d32756b62.png)

**Comment by ianre657** [comment]
目前資料庫中看起來只有一份資料
+ teachers 
{ id:232, name:"荊宇泰", ... }
{ id:4922, name:"鄭昌杰", ... }
+ courses 
{ id:10304, real_id:DCP1241, ch_name:"機器學習概論", ... }
+ course_teacherships
{ id:15575,  course:10304, teacher_id="[232, 4922]"}

應該是其他地方出了問題

**Comment by deror1869107** [comment]
資料庫裡 鄭昌杰 在 Teacher 裡有兩筆資料 id : 7103, 4922
導致 CourseTeachership 和 CourseDetail 有兩筆機器學習概論的資料
